"""HawkAPI CLI — development server launcher and API tools."""

from __future__ import annotations

import argparse
import importlib
import os
import sys
from typing import Any

from hawkapi.openapi.breaking_changes import Change, detect_breaking_changes, format_report
from hawkapi.openapi.schema import generate_openapi


def _parse_ref(ref: str) -> tuple[str, str]:
    """Split an app reference like ``module.path:attr`` into its parts.

    Returns
    -------
    tuple[str, str]
        ``(module_path, attr_name)``
    """
    if ":" not in ref:
        print(
            f"Error: invalid app reference '{ref}'. "
            "Expected format: module:attribute (e.g. main:app)",
            file=sys.stderr,
        )
        sys.exit(1)
    module_path, attr_name = ref.rsplit(":", 1)
    return module_path, attr_name


def _load_app_spec(module_path: str, attr_name: str) -> dict[str, Any]:
    """Import *module_path*, retrieve *attr_name*, and return its OpenAPI spec."""
    try:
        module = importlib.import_module(module_path)
    except ImportError as exc:
        print(f"Error: could not import module '{module_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    app = getattr(module, attr_name, None)
    if app is None:
        print(
            f"Error: module '{module_path}' has no attribute '{attr_name}'",
            file=sys.stderr,
        )
        sys.exit(1)

    if not hasattr(app, "openapi"):
        # Fallback for raw apps: generate spec from routes
        if hasattr(app, "routes"):
            return generate_openapi(
                app.routes,
                title=getattr(app, "title", "HawkAPI"),
                version=getattr(app, "version", "0.1.0"),
            )
        print(
            f"Error: '{module_path}:{attr_name}' does not have an openapi() method",
            file=sys.stderr,
        )
        sys.exit(1)

    return app.openapi()


def _diff_specs(old_spec: dict[str, Any], new_spec: dict[str, Any]) -> list[Change]:
    """Compare two OpenAPI specs and return changes."""
    return detect_breaking_changes(old_spec, new_spec)


def main(argv: list[str] | None = None) -> None:
    """Entry point for the ``hawkapi`` command."""
    parser = argparse.ArgumentParser(
        prog="hawkapi",
        description="HawkAPI development tools",
    )
    subparsers = parser.add_subparsers(dest="command")

    # `hawkapi dev` subcommand
    dev_parser = subparsers.add_parser("dev", help="Start development server")
    dev_parser.add_argument(
        "app",
        help="Application to run (module:attribute format, e.g. main:app)",
    )
    dev_parser.add_argument("--host", default="127.0.0.1", help="Bind host")
    dev_parser.add_argument("--port", type=int, default=8000, help="Bind port")
    dev_parser.add_argument(
        "--reload",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable/disable auto-reload",
    )
    dev_parser.add_argument(
        "--no-uvloop",
        action="store_true",
        default=False,
        help="Disable uvloop even when it is installed (use the default asyncio event loop)",
    )

    # `hawkapi diff` subcommand
    diff_parser = subparsers.add_parser(
        "diff", help="Detect breaking API changes between two app versions"
    )
    diff_parser.add_argument("old", help="Old app reference (module:attr, e.g. myapp.main:app)")
    diff_parser.add_argument("new", help="New app reference (module:attr, e.g. myapp.main:app)")

    # `hawkapi check` subcommand
    check_parser = subparsers.add_parser(
        "check", help="Lint the OpenAPI spec generated by an application"
    )
    check_parser.add_argument(
        "app",
        help="Application to check (module:attribute format, e.g. main:app)",
    )

    # `hawkapi changelog` subcommand
    changelog_parser = subparsers.add_parser(
        "changelog",
        help="Generate Markdown changelog between two app versions",
    )
    changelog_parser.add_argument(
        "old_app",
        help="Old application ref (module:attribute format, e.g. old_app:app)",
    )
    changelog_parser.add_argument(
        "new_app",
        help="New application ref (module:attribute format, e.g. new_app:app)",
    )
    changelog_parser.add_argument(
        "--title",
        default="API Changelog",
        help="Title for the changelog (default: 'API Changelog')",
    )
    changelog_parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path (default: print to stdout)",
    )

    # `hawkapi new` subcommand
    new_parser = subparsers.add_parser("new", help="Create a new HawkAPI project")
    new_parser.add_argument("name", help="Project name")
    new_parser.add_argument("--docker", action="store_true", help="Include Dockerfile")

    # `hawkapi init` subcommand
    subparsers.add_parser("init", help="Initialize HawkAPI configuration in the current directory")

    # `hawkapi gen-client` subcommand
    p_gen = subparsers.add_parser("gen-client", help="Generate a client SDK from OpenAPI")
    p_gen.add_argument("language", choices=["python", "typescript"])
    _source = p_gen.add_mutually_exclusive_group(required=True)
    _source.add_argument("--app", help="module:attr (e.g. myapp.main:app)")
    _source.add_argument("--spec", help="path to openapi.json")
    p_gen.add_argument("--out", required=True, help="output directory")

    # `hawkapi doctor` subcommand
    doctor_parser = subparsers.add_parser(
        "doctor",
        help="Run health checks on a HawkAPI application",
    )
    doctor_parser.add_argument(
        "app",
        help="Application to check (module:attribute format, e.g. main:app)",
    )
    doctor_parser.add_argument(
        "--format",
        dest="output_format",
        choices=["human", "json"],
        default="human",
        help="Output format (default: human)",
    )
    doctor_parser.add_argument(
        "--severity",
        choices=["info", "warn", "error"],
        default="info",
        help="Minimum severity to report (default: info)",
    )
    doctor_parser.add_argument(
        "--fix",
        action="store_true",
        help="Apply safe auto-fixes where available (v1: none implemented)",
    )

    # `hawkapi migrate` subcommand
    migrate_parser = subparsers.add_parser(
        "migrate",
        help="Rewrite a FastAPI codebase to HawkAPI (in place by default)",
    )
    migrate_parser.add_argument(
        "path",
        help="File or directory to migrate. Directories are walked recursively for *.py.",
    )
    migrate_parser.add_argument(
        "--output",
        default=None,
        help="Write migrated files to this directory instead of overwriting.",
    )
    migrate_parser.add_argument(
        "--convert-models",
        action="store_true",
        help="Also rewrite Pydantic BaseModel classes to msgspec.Struct.",
    )
    migrate_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print unified diffs without writing any file.",
    )

    args = parser.parse_args(argv)

    if args.command is None:
        parser.print_help()
        sys.exit(1)

    if args.command == "dev":
        _run_dev(args)
    elif args.command == "diff":
        sys.exit(_run_diff(args))
    elif args.command == "check":
        _run_check(args)
    elif args.command == "changelog":
        _run_changelog(args)
    elif args.command == "new":
        _run_new(args)
    elif args.command == "init":
        _run_init(args)
    elif args.command == "doctor":
        sys.exit(_run_doctor(args))
    elif args.command == "migrate":
        _run_migrate(args)
    elif args.command == "gen-client":
        _run_gen_client(args)


def _run_doctor(args: argparse.Namespace) -> int:
    """Run health checks on the given application and return an exit code."""
    from hawkapi.doctor._formatter import exit_code, format_human, format_json
    from hawkapi.doctor._runner import load_app, run
    from hawkapi.doctor._types import Severity

    module_path, attr_name = _parse_ref(args.app)
    app = load_app(module_path, attr_name)

    _SEV_MAP = {"info": Severity.INFO, "warn": Severity.WARN, "error": Severity.ERROR}
    min_sev = _SEV_MAP[args.severity]

    if args.fix:
        print("--fix: no auto-fixable findings in v1.")

    findings = run(app, min_severity=min_sev)

    if args.output_format == "json":
        print(format_json(findings, args.app))
    else:
        print(format_human(findings, args.app))

    return exit_code(findings)


def _run_dev(args: argparse.Namespace) -> None:
    """Run the development server using uvicorn.

    uvloop is activated automatically when available unless ``--no-uvloop`` is
    passed. This installs ``uvloop.EventLoopPolicy`` before uvicorn starts,
    giving a measurable throughput improvement on Linux/macOS at no extra cost.
    """
    import asyncio

    try:
        import uvicorn  # pyright: ignore[reportMissingImports]
    except ImportError:
        print(
            "Error: uvicorn is required for 'hawkapi dev'. "
            "Install it with: pip install hawkapi[uvicorn]",
            file=sys.stderr,
        )
        sys.exit(1)

    no_uvloop: bool = getattr(args, "no_uvloop", False)
    if not no_uvloop:
        try:
            import uvloop  # type: ignore[import-untyped]  # noqa: PLC0415

            asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())  # pyright: ignore[reportUnknownMemberType,reportUnknownArgumentType]
            print("uvloop event loop policy active")
        except ImportError:
            pass  # uvloop not installed — fall back to default asyncio loop

    print(f"Starting HawkAPI dev server: {args.app}")
    uvicorn.run(  # pyright: ignore[reportUnknownMemberType]
        args.app,
        host=args.host,
        port=args.port,
        reload=args.reload,
    )


def _run_diff(args: argparse.Namespace) -> int:
    """Compare two HawkAPI apps and report breaking changes."""
    old_module_path, old_attr = _parse_ref(args.old)
    new_module_path, new_attr = _parse_ref(args.new)

    old_spec = _load_app_spec(old_module_path, old_attr)
    new_spec = _load_app_spec(new_module_path, new_attr)

    changes = _diff_specs(old_spec, new_spec)

    if not changes:
        print("No API changes detected.")
        return 0

    print(format_report(changes))
    has_breaking = any(c.severity.name == "BREAKING" for c in changes)
    return 1 if has_breaking else 0


def _run_check(args: argparse.Namespace) -> None:
    """Lint the OpenAPI spec generated by an application."""
    from hawkapi.openapi.linter import format_lint_report, lint

    module_path, attr_name = _parse_ref(args.app)
    spec = _load_app_spec(module_path, attr_name)

    issues = lint(spec)
    report = format_lint_report(issues)
    print(report)

    if issues:
        sys.exit(1)


def _run_changelog(args: argparse.Namespace) -> None:
    """Generate a Markdown changelog between two application versions."""
    from hawkapi.openapi.changelog import generate_changelog

    old_module_path, old_attr = _parse_ref(args.old_app)
    new_module_path, new_attr = _parse_ref(args.new_app)

    old_spec = _load_app_spec(old_module_path, old_attr)
    new_spec = _load_app_spec(new_module_path, new_attr)
    changes = _diff_specs(old_spec, new_spec)
    changelog = generate_changelog(changes, title=args.title)

    if args.output:
        with open(args.output, "w") as fh:
            fh.write(changelog)
        print(f"Changelog written to {args.output}")
    else:
        print(changelog)


def _run_new(args: argparse.Namespace) -> None:
    """Scaffold a new HawkAPI project."""
    import os

    from hawkapi._scaffold.templates import generate_project

    project_dir = os.path.join(os.getcwd(), args.name)
    if os.path.exists(project_dir):
        print(f"Error: directory '{args.name}' already exists", file=sys.stderr)
        sys.exit(1)
    generate_project(project_dir, name=args.name, docker=args.docker)
    print(f"Created project '{args.name}' in ./{args.name}/")
    print(f"  cd {args.name} && uv sync && hawkapi dev main:app")


_ENV_CONTENT = """\
# HawkAPI Configuration
# Uncomment and set values as needed.

# DEBUG=true
# PORT=8000
# DATABASE_URL=postgresql://user:password@localhost:5432/dbname
# SECRET_KEY=change-me-to-a-random-secret
"""

_ENV_EXAMPLE_CONTENT = """\
# HawkAPI Configuration
# Copy this file to .env and fill in your values.

DEBUG=true
PORT=8000
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
SECRET_KEY=change-me-to-a-random-secret
"""


def _run_init(args: argparse.Namespace) -> None:
    """Initialize HawkAPI configuration in the current directory."""
    cwd = os.getcwd()
    created: list[str] = []

    for filename, content in [(".env", _ENV_CONTENT), (".env.example", _ENV_EXAMPLE_CONTENT)]:
        filepath = os.path.join(cwd, filename)
        if os.path.exists(filepath):
            print(f"Already exists: {filename}")
        else:
            with open(filepath, "w") as fh:
                fh.write(content)
            created.append(filename)
            print(f"Created: {filename}")

    if created:
        print(f"\nInitialized HawkAPI config ({', '.join(created)})")
    else:
        print("\nNothing to create — all config files already exist.")


def _iter_python_files(root: str) -> list[str]:
    """Return absolute paths to ``*.py`` files under *root* (or [root] if a file)."""
    if os.path.isfile(root):
        return [root] if root.endswith(".py") else []
    found: list[str] = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for fname in filenames:
            if fname.endswith(".py"):
                found.append(os.path.join(dirpath, fname))
    found.sort()
    return found


def _unified_diff(old: str, new: str, label: str) -> str:
    import difflib

    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"a/{label}",
            tofile=f"b/{label}",
        )
    )


def _run_migrate(args: argparse.Namespace) -> None:
    """Migrate a FastAPI codebase to HawkAPI."""
    from hawkapi._migrate.codemod import migrate_file

    if not os.path.exists(args.path):
        print(f"Error: path '{args.path}' does not exist", file=sys.stderr)
        sys.exit(1)

    files = _iter_python_files(args.path)
    if not files:
        print(f"No Python files found under '{args.path}'.")
        return

    src_root = (
        os.path.abspath(args.path)
        if os.path.isdir(args.path)
        else os.path.dirname(os.path.abspath(args.path))
    )
    out_root = os.path.abspath(args.output) if args.output else None

    modified = 0
    total_warnings = 0
    for fpath in files:
        try:
            with open(fpath, encoding="utf-8") as fh:
                source = fh.read()
        except OSError as exc:
            print(f"  skip {fpath}: {exc}", file=sys.stderr)
            continue

        new_source, warnings = migrate_file(source, convert_models=args.convert_models)

        for w in warnings:
            print(f"  warn {fpath}: {w}", file=sys.stderr)
        total_warnings += len(warnings)

        changed = new_source != source

        if args.dry_run:
            if changed:
                rel = os.path.relpath(fpath, src_root) if os.path.isdir(args.path) else fpath
                print(_unified_diff(source, new_source, rel), end="")
                modified += 1
            continue

        if out_root is not None:
            rel = (
                os.path.relpath(fpath, src_root)
                if os.path.isdir(args.path)
                else os.path.basename(fpath)
            )
            dest = os.path.join(out_root, rel)
            os.makedirs(os.path.dirname(dest) or out_root, exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(new_source)
            if changed:
                modified += 1
        elif changed:
            with open(fpath, "w", encoding="utf-8") as fh:
                fh.write(new_source)
            modified += 1

    suffix = " (dry-run)" if args.dry_run else ""
    print(f"Migrated {modified} files, {total_warnings} warnings{suffix}")


def _run_gen_client(args: argparse.Namespace) -> None:
    """Generate a Python or TypeScript client SDK from an OpenAPI spec."""
    import json
    from pathlib import Path

    from hawkapi.openapi.codegen import (
        build_client_ir,
        generate_python_client,
        generate_typescript_client,
    )

    # Resolve the OpenAPI spec dict
    if args.app:
        module_path, attr_name = _parse_ref(args.app)
        spec = _load_app_spec(module_path, attr_name)
    else:
        try:
            with open(args.spec, encoding="utf-8") as fh:
                spec = json.load(fh)
        except (OSError, json.JSONDecodeError) as exc:
            print(f"Error: could not load spec '{args.spec}': {exc}", file=sys.stderr)
            sys.exit(1)

    ir = build_client_ir(spec)

    if args.language == "python":
        source = generate_python_client(ir)
        filename = "client.py"
    else:
        source = generate_typescript_client(ir)
        filename = "client.ts"

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / filename
    out_path.write_text(source, encoding="utf-8")
    print(str(out_path.resolve()))


if __name__ == "__main__":
    main()
