"""HawkAPI CLI — development server launcher and API tools."""

from __future__ import annotations

import argparse
import importlib
import sys
from typing import Any

from hawkapi.openapi.breaking_changes import Change, detect_breaking_changes, format_report
from hawkapi.openapi.schema import generate_openapi


def _parse_ref(ref: str) -> tuple[str, str]:
    """Split an app reference like ``module.path:attr`` into its parts.

    Returns
    -------
    tuple[str, str]
        ``(module_path, attr_name)``
    """
    if ":" not in ref:
        print(
            f"Error: invalid app reference '{ref}'. "
            "Expected format: module:attribute (e.g. main:app)",
            file=sys.stderr,
        )
        sys.exit(1)
    module_path, attr_name = ref.rsplit(":", 1)
    return module_path, attr_name


def _load_app_spec(module_path: str, attr_name: str) -> dict[str, Any]:
    """Import *module_path*, retrieve *attr_name*, and return its OpenAPI spec."""
    try:
        module = importlib.import_module(module_path)
    except ImportError as exc:
        print(f"Error: could not import module '{module_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    app = getattr(module, attr_name, None)
    if app is None:
        print(
            f"Error: module '{module_path}' has no attribute '{attr_name}'",
            file=sys.stderr,
        )
        sys.exit(1)

    if not hasattr(app, "openapi"):
        # Fallback for raw apps: generate spec from routes
        if hasattr(app, "routes"):
            return generate_openapi(
                app.routes,
                title=getattr(app, "title", "HawkAPI"),
                version=getattr(app, "version", "0.1.0"),
            )
        print(
            f"Error: '{module_path}:{attr_name}' does not have an openapi() method",
            file=sys.stderr,
        )
        sys.exit(1)

    return app.openapi()


def _diff_specs(old_spec: dict[str, Any], new_spec: dict[str, Any]) -> list[Change]:
    """Compare two OpenAPI specs and return changes."""
    return detect_breaking_changes(old_spec, new_spec)


def main(argv: list[str] | None = None) -> None:
    """Entry point for the ``hawkapi`` command."""
    parser = argparse.ArgumentParser(
        prog="hawkapi",
        description="HawkAPI development tools",
    )
    subparsers = parser.add_subparsers(dest="command")

    # `hawkapi dev` subcommand
    dev_parser = subparsers.add_parser("dev", help="Start development server")
    dev_parser.add_argument(
        "app",
        help="Application to run (module:attribute format, e.g. main:app)",
    )
    dev_parser.add_argument("--host", default="127.0.0.1", help="Bind host")
    dev_parser.add_argument("--port", type=int, default=8000, help="Bind port")
    dev_parser.add_argument(
        "--reload",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable/disable auto-reload",
    )

    # `hawkapi diff` subcommand
    diff_parser = subparsers.add_parser(
        "diff", help="Detect breaking API changes between two app versions"
    )
    diff_parser.add_argument("old", help="Old app reference (module:attr, e.g. myapp.main:app)")
    diff_parser.add_argument("new", help="New app reference (module:attr, e.g. myapp.main:app)")

    # `hawkapi check` subcommand
    check_parser = subparsers.add_parser(
        "check", help="Lint the OpenAPI spec generated by an application"
    )
    check_parser.add_argument(
        "app",
        help="Application to check (module:attribute format, e.g. main:app)",
    )

    # `hawkapi changelog` subcommand
    changelog_parser = subparsers.add_parser(
        "changelog",
        help="Generate Markdown changelog between two app versions",
    )
    changelog_parser.add_argument(
        "old_app",
        help="Old application ref (module:attribute format, e.g. old_app:app)",
    )
    changelog_parser.add_argument(
        "new_app",
        help="New application ref (module:attribute format, e.g. new_app:app)",
    )
    changelog_parser.add_argument(
        "--title",
        default="API Changelog",
        help="Title for the changelog (default: 'API Changelog')",
    )
    changelog_parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path (default: print to stdout)",
    )

    # `hawkapi new` subcommand
    new_parser = subparsers.add_parser("new", help="Create a new HawkAPI project")
    new_parser.add_argument("name", help="Project name")
    new_parser.add_argument(
        "--docker", action="store_true", help="Include Dockerfile"
    )

    args = parser.parse_args(argv)

    if args.command is None:
        parser.print_help()
        sys.exit(1)

    if args.command == "dev":
        _run_dev(args)
    elif args.command == "diff":
        sys.exit(_run_diff(args))
    elif args.command == "check":
        _run_check(args)
    elif args.command == "changelog":
        _run_changelog(args)
    elif args.command == "new":
        _run_new(args)


def _run_dev(args: argparse.Namespace) -> None:
    """Run the development server using uvicorn."""
    try:
        import uvicorn
    except ImportError:
        print(
            "Error: uvicorn is required for 'hawkapi dev'. "
            "Install it with: pip install hawkapi[uvicorn]",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Starting HawkAPI dev server: {args.app}")
    uvicorn.run(
        args.app,
        host=args.host,
        port=args.port,
        reload=args.reload,
    )


def _run_diff(args: argparse.Namespace) -> int:
    """Compare two HawkAPI apps and report breaking changes."""
    old_module_path, old_attr = _parse_ref(args.old)
    new_module_path, new_attr = _parse_ref(args.new)

    old_spec = _load_app_spec(old_module_path, old_attr)
    new_spec = _load_app_spec(new_module_path, new_attr)

    changes = _diff_specs(old_spec, new_spec)

    if not changes:
        print("No API changes detected.")
        return 0

    print(format_report(changes))
    has_breaking = any(c.severity.name == "BREAKING" for c in changes)
    return 1 if has_breaking else 0


def _run_check(args: argparse.Namespace) -> None:
    """Lint the OpenAPI spec generated by an application."""
    from hawkapi.openapi.linter import format_lint_report, lint

    module_path, attr_name = _parse_ref(args.app)
    spec = _load_app_spec(module_path, attr_name)

    issues = lint(spec)
    report = format_lint_report(issues)
    print(report)

    if issues:
        sys.exit(1)


def _run_changelog(args: argparse.Namespace) -> None:
    """Generate a Markdown changelog between two application versions."""
    from hawkapi.openapi.changelog import generate_changelog

    old_module_path, old_attr = _parse_ref(args.old_app)
    new_module_path, new_attr = _parse_ref(args.new_app)

    old_spec = _load_app_spec(old_module_path, old_attr)
    new_spec = _load_app_spec(new_module_path, new_attr)
    changes = _diff_specs(old_spec, new_spec)
    changelog = generate_changelog(changes, title=args.title)

    if args.output:
        with open(args.output, "w") as fh:
            fh.write(changelog)
        print(f"Changelog written to {args.output}")
    else:
        print(changelog)


def _run_new(args: argparse.Namespace) -> None:
    """Scaffold a new HawkAPI project."""
    import os

    from hawkapi._scaffold.templates import generate_project

    project_dir = os.path.join(os.getcwd(), args.name)
    if os.path.exists(project_dir):
        print(f"Error: directory '{args.name}' already exists", file=sys.stderr)
        sys.exit(1)
    generate_project(project_dir, name=args.name, docker=args.docker)
    print(f"Created project '{args.name}' in ./{args.name}/")
    print(f"  cd {args.name} && uv sync && hawkapi dev main:app")


if __name__ == "__main__":
    main()
