"""HawkAPI CLI — development server launcher."""

from __future__ import annotations

import argparse
import importlib
import sys


def _parse_ref(ref: str) -> tuple[str, str]:
    """Split an app reference like ``module.path:attr`` into its parts.

    Returns
    -------
    tuple[str, str]
        ``(module_path, attr_name)``
    """
    if ":" not in ref:
        print(
            f"Error: invalid app reference '{ref}'. "
            "Expected format: module:attribute (e.g. main:app)",
            file=sys.stderr,
        )
        sys.exit(1)
    module_path, attr_name = ref.rsplit(":", 1)
    return module_path, attr_name


def _load_app_spec(module_path: str, attr_name: str) -> dict:
    """Import *module_path*, retrieve *attr_name*, and return its OpenAPI spec."""
    try:
        module = importlib.import_module(module_path)
    except ImportError as exc:
        print(f"Error: could not import module '{module_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    app = getattr(module, attr_name, None)
    if app is None:
        print(
            f"Error: module '{module_path}' has no attribute '{attr_name}'",
            file=sys.stderr,
        )
        sys.exit(1)

    if not hasattr(app, "openapi"):
        print(
            f"Error: '{module_path}:{attr_name}' does not have an openapi() method",
            file=sys.stderr,
        )
        sys.exit(1)

    return app.openapi()


def main(argv: list[str] | None = None) -> None:
    """Entry point for the ``hawkapi`` command."""
    parser = argparse.ArgumentParser(
        prog="hawkapi",
        description="HawkAPI development tools",
    )
    subparsers = parser.add_subparsers(dest="command")

    # `hawkapi dev` subcommand
    dev_parser = subparsers.add_parser("dev", help="Start development server")
    dev_parser.add_argument(
        "app",
        help="Application to run (module:attribute format, e.g. main:app)",
    )
    dev_parser.add_argument("--host", default="127.0.0.1", help="Bind host")
    dev_parser.add_argument("--port", type=int, default=8000, help="Bind port")
    dev_parser.add_argument(
        "--reload",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable/disable auto-reload",
    )

    # `hawkapi check` subcommand
    check_parser = subparsers.add_parser(
        "check", help="Lint the OpenAPI spec generated by an application"
    )
    check_parser.add_argument(
        "app",
        help="Application to check (module:attribute format, e.g. main:app)",
    )

    args = parser.parse_args(argv)

    if args.command is None:
        parser.print_help()
        sys.exit(1)

    if args.command == "dev":
        _run_dev(args)
    elif args.command == "check":
        _run_check(args)


def _run_dev(args: argparse.Namespace) -> None:
    """Run the development server using uvicorn."""
    try:
        import uvicorn
    except ImportError:
        print(
            "Error: uvicorn is required for 'hawkapi dev'. "
            "Install it with: pip install hawkapi[uvicorn]",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Starting HawkAPI dev server: {args.app}")
    uvicorn.run(
        args.app,
        host=args.host,
        port=args.port,
        reload=args.reload,
    )


def _run_check(args: argparse.Namespace) -> None:
    """Lint the OpenAPI spec generated by an application."""
    from hawkapi.openapi.linter import format_lint_report, lint

    module_path, attr_name = _parse_ref(args.app)
    spec = _load_app_spec(module_path, attr_name)

    issues = lint(spec)
    report = format_lint_report(issues)
    print(report)

    if issues:
        sys.exit(1)


if __name__ == "__main__":
    main()
